mpg_a <-mpg %>% filter(displ<= 4)
mpg_b <- mpg %>% filter(displ>=5)
mean(mpg_a$hwy)
mean(mpg_b$hwy)
install.packages('dplyr')
library('dplyr')
install.packages('ggplot2')
library(ggplot2)
mpg <- as.data.frame(ggplot2::mpg)
mpg_a <- mpg %>% filter(displ<= 4)
mpg_b <- mpg %>% filter(displ>=5)
mean(mpg_a$hwy)
mean(mpg_b$hwy)

