split(iris,iris$Species)
subset(iris, Sepal.Length>=7, select=c('Sepal.Length','Species'))
x <- data.frame(name = c("a", "b", "c"), height = c(170, 180, 160))
y <- data.frame(name = c("c", "b", "a"), weight = c(50, 70, 60))
merge(x,y)
cbind(x,y)
x <- c(1,1,2,2,3,3)
unique(x)
aggregate(Petal.Length ~ Species, iris, mean)
aggregate(cbind(Petal.Length, Sepal.Length) ~ Species, iris, mean)